### ISSUE TITLE
Error on Zigpy connecting to coordinator

### ISSUE THREAD

**Issue by waltervl** [sasu-drooz/Domoticz-Zigate#1860]
I have upgraded my server to Ubuntu 24.06
Upgraded Domoticz to 2025.2 stable.
Setup Python path and installed plugin modules there. No issues.
The plugin gave issues on zigpy.
I installed the plugin completely fresh, without any devices but the error stays the same.
I see the coordinator when doing ls /dev/serial/by-id
ERROR   : [  MainThread 7007] [        WebServer] Certified Device package upgrade results
ERROR   : [  MainThread 7007] [        WebServer] 
ERROR   : [ ZigpyCom_20 7107] [   TransportZigpy] start_zigpy_task error in radio_start: 'App_znp' object has no attribute 'log'
see logs below
[PluginZigbee_20.log](https://github.com/user-attachments/files/22990859/PluginZigbee_20.log)

[PluginZigbee_log_error_history_20.json](https://github.com/user-attachments/files/22990902/PluginZigbee_log_error_history_20.json)

What could be wrong here?????

**Comment by waltervl** [comment]
Update:
I created a venv for zigpy cli and installed it there.
I had to install " sudo apt install python3.12-venv" 
```
python3 -m venv zigpy
source zigpy/bin/activate
pip install zigpy-cli
zigpy radio znp /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0 info
```
Shows
```
PAN ID:                0x4A22
Extended PAN ID:       60:57:50:92:eb:50:8f:37
Channel:               15
Channel mask:          [15]
NWK update ID:         0
Device IEEE:           00:12:4b:00:26:b7:24:f9
Device NWK:            0x0000
Network key:           d8:9d:7d:09:56:97:e5:aa:02:12:34:c5:7a:80:50:47
Network key sequence:  0
Network key counter:   41203469

```
But from Domoticz this does not seem to work....

**Comment by pipiche38** [comment]
I'm wondering if this is not related to python3.12. Do you have a way to test it with a python3.11 ?

**Comment by pipiche38** [comment]
https://github.com/home-assistant/core/issues/115459?utm_source=chatgpt.com

**Comment by pipiche38** [comment]
> on ZHA: As soon as I upgraded Python from 3.12.2 to 3.12.3 ZHA broke. I downgraded python back to 3.12.2 and it is working again.

can you check your python3.12 version ?

**Comment by waltervl** [comment]
I can try it in a docker, see what happens there..

**Comment by waltervl** [comment]
I am on 3.12.3

**Comment by waltervl** [comment]
Yes, on docker stable 2025.2 on Python 3.11.2 it is working......
So for the short term I have to migrate to docker....

Is it going to work in 3.12.3 some time?

**Comment by pipiche38** [comment]
Reported to zigpy for now, to see how they position that issue. https://github.com/zigpy/zigpy/discussions/1691

As Z4D I'll have to setup a bench environment with 3.12.3.

**Comment by pipiche38** [comment]
Tested on debian with 3.12.12 and no issue on Debian 

Duplicating the problem on 3.12.3

> Oct 20 10:40:04 rasp domoticz[37208]: 2025-10-20 10:40:04.822  Status: Zigbee SiliconLab : ++ Started radio ezsp port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230220181151-if00 config {'device': {'path': '/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230220181151-if00', 'baudrate': 115200, 'flow_control': None}, 'network': {}, 'ezsp_config': {}, 'ezsp_policies': {'TRUST_CENTER_POLICY': 3}, 'ota': {}, 'handle_unknown_devices': True}
> Oct 20 10:40:04 rasp domoticz[37208]: 2025-10-20 10:40:04.823  Status: Zigbee SiliconLab : ++ Use of Zigpy Persistent Db
> Oct 20 10:40:04 rasp domoticz[37208]: 2025-10-20 10:40:04.840  Error: Zigbee SiliconLab : start_zigpy_task error in radio_start: 'App_bellows' object has no attribute 'log'
> Oct 20 10:40:04 rasp domoticz[37208]: 2025-10-20 10:40:04.909  Status: Zigbee SiliconLab : Z4D Widgets usage is at 16.9% (212 units free)

**Comment by pipiche38** [comment]
a workaround is set on the rc-stable7.1.024 branch

**Comment by waltervl** [comment]
I will try it this evening...

**Comment by pipiche38** [comment]
then, the best would be to get python3.12 upgraded to a more recent version

**Comment by waltervl** [comment]
Is there a described way to upgrade python so Domoticz uses this upgraded version?

**Comment by pipiche38** [comment]
I used the following on Debian

`sudo apt update && sudo apt upgrade -y`

```
echo "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/deadsnakes-ppa.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA6932366A755776
sudo apt update
```

`sudo apt install -y python3.12 python3.12-venv python3.12-dev`

```
sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.12 12
sudo update-alternatives --config python3
```

For Domoticz python3.12-dev is key, so it is using the most recent sharedlib

PS/ might need to be adapted for Ubuntu

**Comment by waltervl** [comment]
I tried yesterday to upgrade python on my test system (also Ubuntu 24.04) and managed to corrupt it. So I had to reinstall Ubuntu again ...
To be continued.

**Comment by pipiche38** [comment]
@waltervl did you succeed to upgrade your python environment ?

**Comment by waltervl** [comment]
Not yet...

**Comment by pipiche38** [comment]
Hello @waltervl if you don't mind, I'll close this issue. Feel free to re-open if you still have the issue

**Comment by waltervl** [comment]
No problem, I tried it lately with pyenv to upgrade python to 3.12.12 but Domoticz did still not use it...
I am running Domoticz in a Docker now (with python 3.11)
